GET http://localhost:8080/couponbook/list/findall
Accept: application/json

GET http://localhost:8080/couponbook/list/test2
Accept: application/json


### 7. 만료 3일 전, 아직 사용 안된 쿠폰 목록 조회 API (단, 사용자에게 지급된 쿠폰 중에서)
GET http://localhost:8080/couponbook/list/expire/notice
Accept: application/json

### 6. 당일 만료된 쿠폰 목록 조회 API
GET http://localhost:8080/couponbook/list/expire
Accept: application/json

### 5. 쿠폰 사용 취소 API (취소된 쿠포는 재사용 가능)
PUT http://localhost:8080/couponbook/cancel
Content-Type: application/json

{
  "coupon_id" : "Okqhk-okM7B-ce5ViURy"
}

### 4. 쿠폰 사용 API (재사용 불가)
PUT http://localhost:8080/couponbook/use
Content-Type: application/json

{
  "coupon_id" : "Okqhk-okM7B-ce5ViURy"
}

### 3. 사용자에게 지급된 쿠폰 목록 조회 API
GET http://localhost:8080/couponbook/list/issue
Accept: application/json

### 2. 쿠폰 지급 API
PUT http://localhost:8080/couponbook/issue
Content-Type: application/json

{
}

### 1. 랜덤 쿠폰 생성 API
POST http://localhost:8080/couponbook/create
Content-Type: application/json

{
  "cnt": 5
}